name: Build and Release v1

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild & NuGet
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Build Project
      shell: pwsh
      run: |
        $projectFile = Get-ChildItem -Recurse -Filter "*.csproj" | Select-Object -First 1 -ExpandProperty FullName
        nuget restore "$projectFile"
        # Force the output to the publish folder
        msbuild "$projectFile" /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath="${{ github.workspace }}\publish\"

    - name: Build Installer (Inno Setup)
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: installer.iss

    - name: Create or Update Release v1
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0
        name: Release v1.0
        draft: false
        prerelease: false
        files: setup_output/Optimizer-v1-Setup.exe
        make_latest: true
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


